branch-defaults:
  freelance-updates:
    environment: Sweatapp-env
    group_suffix: null
  master:
    environment: Sweatapp-env
    group_suffix: null
environment-defaults:
  Sweatapp-env:
    branch: null
    repository: null
global:
  application_name: sweat-app
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: git
  workspace_type: Application
