on:
  push:
    branches:
      - master
      - freelance-updates

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli==3.20.3

      - name: Verify EB CLI Installation
        run: eb --version

      - name: Deploy to EBS
        run: |
          eb deploy
